[build]
  publish = "."
  command = ""   # leave empty since you don’t need a build step

#Minify JS and CSS
[build.processing.css]
  minify = true
  bundle = false

[build.processing.js]
  minify = true
  bundle = false

# Critical CSS
[[plugins]]
  package = "netlify-plugin-inline-critical-css"
  [plugins.inputs]
    fileFilter = [
      "index.html",
      "about.html",
      "bmi.html",
      "emi.html",
      "sip.html",
      "gst.html",
      "tax.html",
      "age.html",
      "discount.html",
      "fuel.html",
      "gold.html",
      "percentage.html",
      "privacy.html",
      "terms.html"
    ]

# Cache busting
[[plugins]]
package = "netlify-plugin-hashfiles"
  [plugins.inputs]
  staticDir = "."
  entryPoints = ["index.html", "about.html", "age.html", "bmi.html", "discount.html", "emi.html", "fuel.html", "gold.html", "gst.html", "percentage.html", "privacy.html", "sip.html", "tax.html", "terms.html"]

# Minify HTML
[[plugins]]
  package = "netlify-plugin-minify-html"

# Submit sitemap
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
    sitemapPath = "sitemap.xml"
    providers = ["google"]
