[build]
  publish = "."
  command = ""   # leave empty since you don’t need a build step

# Cache busting
[[plugins]]
  package = "netlify-plugin-hashfiles"
  [plugins.inputs]
    directory = "."

# Critical CSS
[[plugins]]
  package = "netlify-plugin-inline-critical-css"
  [plugins.inputs]
    fileFilter = [
      "index.html",
      "about.html",
      "bmi.html",
      "emi.html",
      "sip.html",
      "gst.html",
      "tax.html",
      "age.html",
      "discount.html",
      "fuel.html",
      "gold.html",
      "percentage.html",
      "privacy.html",
      "terms.html"
    ]


# Minify HTML
[[plugins]]
  package = "netlify-plugin-minify-html"

# Fonts
[[plugins]]
package = "netlify-plugin-subfont"
  [plugins.inputs]
  recursive = true
  inlineFonts = true
  fontDisplay = "swap"
  entryPoints = [
      "index.html",
      "about.html",
      "bmi.html",
      "emi.html",
      "sip.html",
      "gst.html",
      "tax.html",
      "age.html",
      "discount.html",
      "fuel.html",
      "gold.html",
      "percentage.html",
      "privacy.html",
      "terms.html"]


# Submit sitemap
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
    sitemapPath = "sitemap.xml"
    providers = ["google"]
